### ISSUE TITLE
whats the difference between frontend captions and backend ?

### ISSUE THREAD

**Issue by ghost** [Davenchy/live-torrent-backend#50]
i'm wondering what why there is 2 str to vtt ?

https://github.com/Davenchy/live-torrent/blob/master/src/utils/captions.js#L66

and

https://github.com/Davenchy/live-torrent-backend/blob/3adc8d7816f51bba237c95ecef34bd5d35951d5c/services/captions.js#L126

**Comment by Davenchy** [comment]
I created Live Torrent project at the beginning as one package frontend and backend, then I splitted it into to projects frontend (live-torrent) and backend (live-torrent-backend) so I can develop each part on its own.
I am trying to add all APIs I need in the backend then I am going to remove it totally from the frontend and right now I am working on it.
