### ISSUE TITLE
Beware with Heroku deployments

### ISSUE THREAD

**Issue by pataquets** [Davenchy/live-torrent-backend#74]
As reported on KiraLT/torrent-stream-server#32.
Actually, the app which got my account suspended in the end was live-torrent-backend.
FYI.

**Comment by Davenchy** [comment]
I am really sorry about that, and thanks for notifying me.

**Comment by pataquets** [comment]
No worries, thanks @Davenchy . Anyway, I should have been more cautious with the software I was deploying. Only me to blame 😉 . Fortunately, my account it's now reinstated.
I notified to avoid others clicking without thinking too much (as I did) to get in trouble. Thank you for taking measures.
